services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plaid-api
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/core/db
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped